# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ee/ci/yaml/README.html for all available options

before_script:
  - echo "start deploy"
  - echo "setup java environment for Ubuntu 20.04"
  - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 

deploy1:
  stage: deploy
  script:
    - mvn clean deploy
